[package]
name = "activities"
version = "0.1.0"
authors = [""]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
humantime = "2.1.0" # For a26
chrono = "0.4.19" # For a26
thiserror = "1.0.29"
